# Generated by Django 4.2 on 2023-08-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='eee', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
